theme: jekyll-theme-midnight

baseurl: /patra

title: Patra
description: Visualizer of Dropwizard Metrics

author: Indra Basak

logo: ./src/images/logo-blue_40px.png
#docs:
demo: ./demo/index.html
blog: https://indrabasak.github.io